
#include <global_vars.h>
#include <blocks.h>
#include <main.h>
#include <entities.h>
#include <effects.h>
#include <loadg.h>
#include <backgrounds.h>
#include <objects.h>
#include <lifts.h>
#include <player.h>

#include "levels.h"

//From SA : All Stars
void HandleKaizoSyobonLevels()
{
    StageClear(); //+KZ added

    if(SyobonState == ESyobonGameState::TITLE)
    {
        scrollx = 0;

        PlayerX = (2 * 30) * 100;
        PlayerY = (12 * 29 - 12 - 6) * 100;

        BlockCreate(2, 13, EBlockType::GROUND_TOP);
        BlockCreate(2, 14, EBlockType::GROUND_BOTTOM);

        return;
    }

    scrollx = 360000;

    if (SyobonWorld == 1 && SyobonLevel == 1 && SyobonSection == 0)
    {
        ELegacyStageDate stagedatexKaizo1[17][1001] =
			{
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GOAL_POLE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GOAL_POLE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GOAL_POLE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GOAL_POLE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, SPIKE, SPIKE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, NONE, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, STAGEDATE_98, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, SPIKE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, NONE, HARD_BLOCK, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN,
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					BALL, NONE, SPIKE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					TREE, NONE, NONE, TREE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, CASTLE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					CHECKPOINT, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GRASS,
					NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, BALL, NONE, BALL, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, GRASS, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, GROUND_TOP, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP
				},
				{
					NONE, NONE, NONE, GROUND_BOTTOM, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_BOTTOM, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_BOTTOM, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_BOTTOM, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE, NONE, GROUND_BOTTOM, NONE, NONE, NONE,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					NONE, NONE, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, ITEM_BLOCK_OPEN, ITEM_BLOCK_OPEN, ITEM_BLOCK_OPEN, NONE, NONE, ITEM_BLOCK_OPEN, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE
				}
			};

        bgmchange(Music[1]);
        PlayerGroundType = EPlayerGroundType::NORMAL;
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_1;
        BlockCreateLegacy(58, 249, EBlockType::MESSAGE_BLOCK);
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_2;
        BlockCreateLegacy(870, 191, EBlockType::MESSAGE_BLOCK);
        for (int num143 = 0; num143 <= 1000; num143++)
        {
            for (int num144 = 0; num144 <= 16; num144++)
            {
                LegacyStageDate[num144][num143] = stagedatexKaizo1[num144][num143];
            }
        }
    }
    if (SyobonWorld == 1 && SyobonLevel == 2 && SyobonSection == 0)
    {
        ELegacyStageDate stagedatexKaizo2[17][1001] =
			{
				{
					SPIKE, SPIKE, SPIKE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK,
					HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, SPIKE, SPIKE, HARD_BLOCK, SPIKE, SPIKE, SPIKE, HARD_BLOCK,
					SPIKE, SPIKE, HARD_BLOCK, SPIKE, SPIKE, SPIKE, SPIKE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE
				},
				{
					HARD_BLOCK, NONE, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, GOAL_POLE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, BRICK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GOAL_POLE
				},
				{
					SPIKE, NONE, SPIKE, SPIKE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BRICK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, BRICK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					HORIZONTAL_PIPE_HEAD, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY, HORIZONTAL_PIPE_BODY
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, BRICK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, BRICK, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE
				},
				{
					GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, BRICK, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP
				},
				{
					GROUND_BOTTOM, GROUND_BOTTOM, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_BOTTOM, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
					GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_TOP, NONE, NONE,
					NONE
				}
			};

        bgmchange(Music[2]);
        PlayerGroundType = EPlayerGroundType::NORMAL;
        LevelType = ELevelType::UNDERGROUND;
        scrollx = 408000;
        BlockCount = 0;
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_3;
        BlockCreateLegacy(0, 249, EBlockType::MESSAGE_BLOCK);
        ObjectCount = 0;
        int num145 = ObjectCount;
        ObjectX[num145] = 40600;
        ObjectY[num145] = 24900;
        ObjectSizeX[num145] = 6000;
        ObjectSizeY[num145] = 11800;
        ObjectType[num145] = EObjectType::ENTRANCE_VERTICAL_PIPE_HEAD;
        ObjectSubType[num145] = EObjectSubType::ENTRACE_VERTICAL_PIPE_HEAD_GO_NEXT_SECTION;
        ObjectCount++;
        for (int num146 = 0; num146 <= 1000; num146++)
        {
            for (int num147 = 0; num147 <= 16; num147++)
            {
                LegacyStageDate[num147][num146] = stagedatexKaizo2[num147][num146];
            }
        }
    }
    if (SyobonWorld == 1 && SyobonLevel == 2 && SyobonSection == 1)
    {
        ELegacyStageDate stagedatexKaizo3[17][1001] =
			{
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{NONE},
				{
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_BOTTOM,
					NONE, NONE, NONE, NONE, NONE, GROUND_BOTTOM, NONE, NONE, NONE
				},
				{NONE}
			};
        bgmchange(Music[2]);
        PlayerGroundType = EPlayerGroundType::NORMAL;
        scrollx = 0;
        PlayerX = 6000;
        PlayerY = 3000;
        LevelType = ELevelType::UNDERGROUND;
        for (int num148 = 0; num148 <= 1000; num148++)
        {
            for (int num149 = 0; num149 <= 16; num149++)
            {
                LegacyStageDate[num149][num148] = stagedatexKaizo3[num149][num148];
            }
        }
    }
    if (SyobonWorld == 1 && SyobonLevel == 3 && SyobonSection == 6)
    {
        SyobonSection = 0;
    }
    if (SyobonWorld == 1 && SyobonLevel == 3 && SyobonSection == 0)
    {
        ELegacyStageDate stagedatexKaizo5[17][1001] =
			{
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
					HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, SPIKE, SPIKE, SPIKE, SPIKE,
					SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE,
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE,
					GOAL_POLE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GOAL_POLE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, BRICK, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, ITEM_BLOCK_COIN, NONE, NONE, HARD_BLOCK,
					HARD_BLOCK, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, BRICK, NONE, NONE, NONE,
					BRICK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					SPIKE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					BRICK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK,
					NONE, HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, SPIKE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE,
					NONE, NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{NONE},
				{
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
                    NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, CASTLE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, CASTLE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE
                },
                    {
                    HORIZONTAL_PIPE_HEAD, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
                },
				{
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE
                },
				{
                    GROUND_TOP, BALL, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
                    NONE, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    GROUND_TOP, NONE, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
                    GROUND_TOP, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
                    NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE
                },
				{
                    GROUND_BOTTOM, NONE, NONE, NONE, NONE, GROUND_BOTTOM, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    GROUND_BOTTOM, NONE, GROUND_BOTTOM, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE,
                    GROUND_BOTTOM, NONE, NONE, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM,
                    NONE, NONE, NONE, NONE, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, GROUND_BOTTOM, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE
                },
				{
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, HARD_BLOCK,
                    HARD_BLOCK, HARD_BLOCK, NONE, NONE, NONE, NONE, NONE, HARD_BLOCK, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
                    NONE, NONE, NONE, NONE, NONE
                }
			};
        stagedatexKaizo5[9][49] = HARD_BLOCK;
        stagedatexKaizo5[9][57] = HARD_BLOCK;
		

        PlayerGroundType = EPlayerGroundType::SLIP;
        bgmchange(Music[1]);
        LevelType = ELevelType::KAIZO_SYOBON_OVERWORLD_SLIP;
        scrollx = 390000;
        PlayerY = 33720;
        BlockCount = 0;
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_4;
        BlockCreateLegacy(0, 220, EBlockType::MESSAGE_BLOCK);
        BlockCreateLegacy(1566, 278, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1450, 278, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1624, 278, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1450, 191, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1508, 191, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1566, 191, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1450, 104, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1508, 104, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1566, 104, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockCreateLegacy(1624, 104, EBlockType::ITEM_BLOCK_POISON_HIDDEN);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(1711, 133, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(1740, 133, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(1856, 75, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(1885, 75, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2001, 133, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2059, 133, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2146, 104, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2175, 104, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2291, 104, EBlockType::BRICK_BRITTLE);
        BlockSubType[BlockCount] = EBlockSubType::BRICK_BRITTLE_BRICK;
        BlockCreateLegacy(2349, 104, EBlockType::BRICK_BRITTLE);
        BlockCreateLegacy(2639, 307, EBlockType::KAIZO_SYOBON_ITEM_BLOCK_105);
        LiftCount = 0;
        LiftX[LiftCount] = 5800;
        LiftY[LiftCount] = 7500;
        LiftSizeX[LiftCount] = 18000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 1;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::KAIZO_SYOBON_UNKNOWN_13;
        LiftTouchSpeedUp[LiftCount] = false;
        LiftCount++;
        LiftX[LiftCount] = 29000;
        LiftY[LiftCount] = 13300;
        LiftSizeX[LiftCount] = 15000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::PILLAR_BOUNCY;
        LiftTouchSpeedUp[LiftCount] = false;
        LiftCount++;
        LiftX[LiftCount] = 52200;
        LiftY[LiftCount] = 16200;
        LiftSizeX[LiftCount] = 18000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::KAIZO_SYOBON_UNKNOWN_13;
        LiftTouchSpeedUp[LiftCount] = false;
        LiftCount++;
        LiftX[LiftCount] = 75400;
        LiftY[LiftCount] = 19100;
        LiftSizeX[LiftCount] = 9000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::BREAKING;
        LiftCount++;
        LiftX[LiftCount] = 90800;
        LiftY[LiftCount] = 13300;
        LiftSizeX[LiftCount] = 9000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::BREAKING;
        LiftCount++;
        LiftX[LiftCount] = 108200;
        LiftY[LiftCount] = 1700;
        LiftSizeX[LiftCount] = 9000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::BREAKING;
        LiftCount++;
        LiftX[LiftCount] = 275500;
        LiftY[LiftCount] = 16200;
        LiftSizeX[LiftCount] = 19000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::KAIZO_SYOBON_UNKNOWN_13;
        LiftTouchSpeedUp[LiftCount] = false;
        LiftCount++;
        LiftX[LiftCount] = 304500;
        LiftY[LiftCount] = 24900;
        LiftSizeX[LiftCount] = 39000;
        LiftInteractType[LiftCount] = 0;
        LiftMovementType[LiftCount] = 0;
        LiftVelY[LiftCount] = 0;
        LiftType[LiftCount] = ELiftType::KAIZO_SYOBON_UNKNOWN_13;
        LiftTouchSpeedUp[LiftCount] = false;
        LiftCount++;
        BlockCreateLegacy(522, 394, EBlockType::NOTE_BLOCK);
        BlockCreateLegacy(551, 394, EBlockType::NOTE_BLOCK);
        BlockCreateLegacy(580, 394, EBlockType::NOTE_BLOCK);
        BlockCreateLegacy(2146, 249, EBlockType::ITEM_BLOCK_HIDDEN);
        int num150 = ObjectCount;
        ObjectX[num150] = 26100;
        ObjectY[num150] = 36500;
        ObjectSizeX[num150] = 8999;
        ObjectSizeY[num150] = 3000;
        ObjectType[num150] = EObjectType::FALLING_FLOOR;
        ObjectCount++;
        num150 = ObjectCount;
        ObjectX[num150] = 378400;
        ObjectY[num150] = -1300;
        ObjectSizeX[num150] = 15000;
        ObjectSizeY[num150] = 14000;
        ObjectType[num150] = EObjectType::TRIGGER_MULTI_LASER;
        ObjectCount++;
        EnemyAppearCount = 0;
        EnemyAppearX[EnemyAppearCount] = 258100;
        EnemyAppearY[EnemyAppearCount] = 30700;
        EnemyAppearType[EnemyAppearCount] = EEnemyType::SPIKY_BLOCK;
        EnemyAppearSubType[EnemyAppearCount] = EEnemySubType::SPIKY_BLOCK_HARD_BLOCK;
        EnemyAppearCount++;
        EnemyAppearX[EnemyAppearCount] = 300;
        EnemyAppearY[EnemyAppearCount] = 4600;
        EnemyAppearType[EnemyAppearCount] = EEnemyType::EVIL_CLOUD;
        EnemyAppearSubType[EnemyAppearCount] = EEnemySubType::EVIL_CLOUD_NORMAL;
        EnemyAppearCount++;
        if (stagepoint)
        {
            stagepoint = false;
            PlayerX = 4500;
            PlayerY = -3000;
            CurrentPlayerCheckpoint = 0;
        }
        for (int num151 = 0; num151 <= 1000; num151++)
        {
            for (int num152 = 0; num152 <= 16; num152++)
            {
                LegacyStageDate[num152][num151] = stagedatexKaizo5[num152][num151];
            }
        }
    }
    if (SyobonWorld == 1 && SyobonLevel == 3 && SyobonSection == 5)
    {
        ELegacyStageDate stagedatexKaizo7[17][1001] =
			{
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE,
					NONE, NONE, NONE, NONE
				},
				{NONE},
				{NONE},
				{
					NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, COIN, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, CLOUD_BLOCK, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, COIN, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, COIN
				},
				{
					NONE, NONE, ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, CLOUD_BLOCK, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, CLOUD_BLOCK
				},
				{
					NONE, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					COIN, NONE, NONE, NONE
				},
				{
					COIN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					CLOUD_BLOCK, NONE, NONE, NONE
				},
				{
					CLOUD_BLOCK, NONE, COIN, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, CLOUD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{NONE},
				{
					NONE, CLOUD_BLOCK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{NONE},
				{NONE}
			};

        LevelType = ELevelType::KAIZO_SYOBON_OVERWORLD_SLIP;
        PlayerGroundType = EPlayerGroundType::SLIP;
        bgmchange(Music[3]);
        scrollx = 0;
        PlayerX = 3000;
        PlayerY = 33000;
        stagepoint = true;
        ObjectCount = 0;
        int num153 = ObjectCount;
        ObjectX[num153] = 40595;
        ObjectY[num153] = 30700;
        ObjectSizeX[num153] = 6000;
        ObjectSizeY[num153] = 14800;
        ObjectType[num153] = EObjectType::ENTRANCE_VERTICAL_PIPE_HEAD;
        ObjectSubType[num153] = EObjectSubType::ENTRACE_VERTICAL_PIPE_HEAD_GO_NEXT_SECTION;
        ObjectCount++;
        BlockSubType[BlockCount] = EBlockSubType::NONE;
        BlockCreateLegacy(377, 75, EBlockType::ITEM_BLOCK_COINS);
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_5;
        BlockCreateLegacy(377, -12, EBlockType::MESSAGE_BLOCK);
        for (int num154 = 0; num154 <= 1000; num154++)
        {
            for (int num155 = 0; num155 <= 16; num155++)
            {
                LegacyStageDate[num155][num154] = stagedatexKaizo7[num155][num154];
            }
        }
    }
    if (SyobonWorld == 1 && SyobonLevel == 4 && SyobonSection == 0)
    {
        ELegacyStageDate stagedatexKaizo8[17][1001] =
			{
				{
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, NONE, NONE, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, VERTICAL_PIPE_BODY, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, NONE, NONE, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, VERTICAL_PIPE_BODY, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, BRICK, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, NONE, HORIZONTAL_PIPE_HEAD, HORIZONTAL_PIPE_BODY, VERTICAL_PIPE_BODY, GROUND_TOP, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, VERTICAL_PIPE_BODY, GROUND_TOP, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, GOAL_POLE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, ITEM_BLOCK_HIDDEN, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE,
					SPIKE, SPIKE, GROUND_TOP, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, BRICK, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, GROUND_TOP,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, GROUND_TOP, SPIKE, SPIKE,
					SPIKE, SPIKE, ITEM_BLOCK_HIDDEN, SPIKE, SPIKE, SPIKE, SPIKE, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, SPIKE, SPIKE, NONE,
					NONE, FLAME, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, SUPER_BOON, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, ITEM_BLOCK_HIDDEN, GROUND_TOP, NONE, GROUND_TOP, ITEM_BLOCK_HIDDEN,
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, SPIKE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, FLAME, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, GROUND_TOP, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					ITEM_BLOCK_HIDDEN, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, GROUND_TOP,
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, ITEM_BLOCK_HIDDEN, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, FLAME,
					NONE, GROUND_TOP, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, BALL_SHELLED, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, GROUND_TOP, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, FLAME,
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BRICK,
					BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, ITEM_BLOCK_HIDDEN, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, FLAME,
					NONE, GROUND_TOP, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, GROUND_TOP, LAVA, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
					NONE, NONE, NONE, NONE, NONE, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP, GROUND_TOP,
					GROUND_TOP, GROUND_TOP, GROUND_TOP, NONE, NONE, NONE, NONE, NONE, NONE
				},
				{NONE}
			};

        bgmchange(Music[6]);
        scrollx = 440000;
        PlayerX = 12000;
        PlayerY = 6000;
        LevelType = ELevelType::CASTLE;
        ObjectCount = 0;
        int num156 = ObjectCount;
        BlockSubType[BlockCount] = EBlockSubType::MESSAGE_BLOCK_KAIZO_SYOBON_6;
        BlockCreateLegacy(58, 46, EBlockType::MESSAGE_BLOCK);
        EnemyAppearCount = 0;
        EnemyAppearX[EnemyAppearCount] = 8700;
        EnemyAppearY[EnemyAppearCount] = 7500;
        EnemyAppearType[EnemyAppearCount] = EEnemyType::EVIL_CLOUD;
        EnemyAppearSubType[EnemyAppearCount] = EEnemySubType::EVIL_CLOUD_HIDDEN;
        EnemyAppearCount++;
        SyobonSection = 0;
        for (int num157 = 0; num157 <= 1000; num157++)
        {
            for (num156 = 0; num156 <= 16; num156++)
            {
                LegacyStageDate[num156][num157] = stagedatexKaizo8[num156][num157];
            }
        }
    }
}
