name: Build Release Artifacts

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Prepare Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
          libusb-1.0-0-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Install SDL3
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest

      - name: Build SyobonKZ
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Prepare artifact
        run: |
          cd build
          mkdir SyobonKZ-Linux
          mv ./SyobonKZ ./SyobonKZ-Linux/
          mv ./res ./SyobonKZ-Linux/
          mv ./BGM ./SyobonKZ-Linux/
          mv ./SE ./SyobonKZ-Linux/
          mv ./text ./SyobonKZ-Linux/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-ubuntu-22.04
          path: build/SyobonKZ-Linux


  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-sdl3
            mingw-w64-x86_64-sdl3-image
            mingw-w64-x86_64-sdl3-mixer
            mingw-w64-x86_64-sdl3-ttf

      - name: Build SyobonKZ
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
          mingw32-make

      - name: Prepare artifact
        run: |
          cd build
          mkdir SyobonKZ-Windows
          mv ./SyobonKZ.exe ./SyobonKZ-Windows/
          mv ./res ./SyobonKZ-Windows/
          mv ./BGM ./SyobonKZ-Windows/
          mv ./SE ./SyobonKZ-Windows/
          mv ./text ./SyobonKZ-Windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-windows
          path: build/SyobonKZ-Windows
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Prepare badOS
        run: |
          brew install cmake sdl3

      - name: Build SyobonKZ
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Prepare artifact
        run: |
          cd build
          mkdir SyobonKZ-macOS
          mv ./SyobonKZ.app ./SyobonKZ-macOS/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-macOS-14
          path: build/SyobonKZ-macOS
          
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Prepare Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install ninja-build openssl cmake

      - name: Restore keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > "$GITHUB_WORKSPACE/release.jks"
      
      # Github ubuntu 22.04 runner already has a android SDK (27 by default)
      - name: Build SyobonKZ
        run: |
          export PATH="$PATH:$ANDROID_HOME/platform-tools/"
          export JAVA_HOME="$JAVA_HOME_17_X64"
          cd android-project && ./gradlew build \
            -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/release.jks" \
            -Pandroid.injected.signing.store.password="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.ANDROID_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.ANDROID_KEY_PASSWORD }}"

      - name: Prepare artifact
        run: |
          cd ./android-project/app/build/outputs/apk/release/
          mkdir SyobonKZ-Android
          mv app-release.apk ./SyobonKZ-Android/SyobonKZ.apk
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-android
          path: android-project/app/build/outputs/apk/release/SyobonKZ-Android

