name: Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Prepare Linux
        run: |
          sudo apt-get update -y
          sudo apt install build-essential git
          sudo apt-get install libsdl1.2-compat-dev cmake

      - name: Build SyobonKZ
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Prepare artifact
        run: |
          cd build
          mkdir SyobonKZ-Linux
          mv ./SyobonAction ./SyobonKZ-Linux/
          mv ./res ./SyobonKZ-Linux/
          mv ./BGM ./SyobonKZ-Linux/
          mv ./SE ./SyobonKZ-Linux/
          mv ./lib ./SyobonKZ-Linux/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-ubuntu-22.04
          path: build/SyobonKZ-Linux


  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: x86
        
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32
          update: true
          install: >
            mingw-w64-i686-toolchain
            mingw-w64-i686-cmake
            mingw-w64-i686-make
            mingw-w64-i686-sdl12-compat
            mingw-w64-i686-SDL2

      - name: Build SyobonKZ
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
          make

      - name: Prepare artifact
        run: |
          cd build
          mkdir SyobonKZ-Windows
          mv ./SyobonAction ./SyobonKZ-Windows/
          mv ./res ./SyobonKZ-Windows/
          mv ./BGM ./SyobonKZ-Windows/
          mv ./SE ./SyobonKZ-Windows/
          mv ./lib ./SyobonKZ-Windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyobonKZ-windows-32
          path: build/SyobonKZ-Windows
